# Generated by Django 4.0.5 on 2022-07-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_datasetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usermovieid',
            field=models.IntegerField(default=0),
        ),
    ]
