# Generated by Django 4.0.5 on 2022-07-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_usermovieid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('genres', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('mean', models.FloatField()),
                ('count', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
